#!/bin/bash
# Conventional commit message format check.
# Copy to ".git/hooks".

# Function to check if a commit message follows conventional commit rules
check_commit_message() {
	commit_msg_file=$1

	# Fetch the commit message
	commit_msg=$(cat "$commit_msg_file")

	# Define regex pattern for conventional commit format
	pattern="^(feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?: .{1,100}"

	# Check if the commit message matches the pattern
	if [[ ! $commit_msg =~ $pattern ]]; then
		echo "Invalid commit message format!"
		echo "Please follow the conventional commit format: type(scope): message (max 100 characters)"
		exit 1
	fi
}

# Check commit message for conventional format
check_commit_message "$1"

# If no issues found, exit successfully
exit 0
