#!/usr/bin/env python3

import argparse
import secrets
import string
import sys

VERSION = "%(prog)s 1.0.0"
DEFAULT_PASSWORD_LENGTH = 32


def parse_arguments():
    parser = argparse.ArgumentParser(description="Generate random password.")
    parser.add_argument(
        "-v",
        "--version",
        action="version",
        version=VERSION,
        help="show program version and exit",
    )
    parser.add_argument(
        "-l",
        "--length",
        metavar="length",
        type=int,
        default=DEFAULT_PASSWORD_LENGTH,
        help=f"specify password length (default: {DEFAULT_PASSWORD_LENGTH})",
    )
    args = parser.parse_args()
    return args


def print_error(message: str) -> None:
    sys.stderr.write(f"Error: {message}\n\n")


def terminate_execution(message: str) -> None:
    exit_code: int = 1
    print_error(message)
    sys.exit(exit_code)


def generate_password(length: int) -> str:
    allowed_characters = string.ascii_letters + string.digits + string.punctuation

    password = "".join(secrets.choice(allowed_characters) for _ in range(length))

    return password


def main():
    args = parse_arguments()
    password = generate_password(args.length)
    sys.stdout.write(f"{password}")


if __name__ == "__main__":
    main()
