#!/usr/bin/env python3
#
# Generate random password.
#
# Author: Michal Svorc <dev@michalsvorc.com>
# License: MIT license (https://opensource.org/licenses/MIT)
# Guidelines: https://google.github.io/styleguide/pyguide

import argparse
import secrets
import string
import sys

VERSION = "1.0.0"
PASSWORD_LENGTH_DEFAULT = 32


def main():
    args = parse_arguments()
    password = generate_password(args.length)
    sys.stdout.write(f"{password}")


def parse_arguments():
    parser = argparse.ArgumentParser(description="Generate random password.")
    parser.add_argument(
        "-v",
        "--version",
        action="version",
        version=f"%(prog)s {VERSION}",
        help="show program version and exit",
    )
    parser.add_argument(
        "-l",
        "--length",
        metavar="length",
        type=int,
        default=PASSWORD_LENGTH_DEFAULT,
        help=f"specify password length (default: {PASSWORD_LENGTH_DEFAULT})",
    )
    args = parser.parse_args()
    return args


def generate_password(length: int) -> str:
    allowed_characters = string.ascii_letters + string.digits + string.punctuation

    password = "".join(secrets.choice(allowed_characters) for _ in range(length))

    return password


if __name__ == "__main__":
    main()
