#!/usr/bin/env bash

#===============================================================================
# Compile Neovim binary
# Link: https://github.com/neovim/neovim
#===============================================================================

tag='nightly'
repository='neovim/neovim'

curl -L "https://github.com/${repository}/archive/refs/tags/${tag}.tar.gz" |
	tar -xz

cd "neovim-${tag}" &&
	make CMAKE_BUILD_TYPE=Release &&
	printf 'Installing compiled %s\n' "${repository} ${tag}" &&
	sudo make install
